/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicButtonUI;

/**
 *
 * @author hoang
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainGUI() {
        initComponents();
        
        JButton[] btns = {btn_home};
        for (JButton btn : btns) {
            btn.setBackground(new Color(51, 66, 87));
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {

                }

                @Override
                public void mousePressed(MouseEvent e) {

                }

                @Override
                public void mouseReleased(MouseEvent e) {

                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(84, 140, 168));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(new Color(51, 66, 87));
                }
            });
        }
        
        btn_exit.setBackground(new Color(51, 66, 87));
        btn_exit.setUI(new BasicButtonUI());
        btn_exit.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {

            }

            @Override
            public void mousePressed(MouseEvent e) {

            }

            @Override
            public void mouseReleased(MouseEvent e) {

            }

            @Override
            public void mouseEntered(MouseEvent e) {
                btn_exit.setBackground(new Color(182, 25, 25));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                btn_exit.setBackground(new Color(51, 66, 87));
            }
        });
    }
    
    // Switch panel
    private void switchPanels(JPanel panelTop, JPanel panelBot) {
        layeredPaneTop.removeAll();
        layeredPaneBot.removeAll();

        layeredPaneTop.add(panelTop);
        layeredPaneBot.add(panelBot);

        layeredPaneTop.repaint();
        layeredPaneBot.repaint();

        layeredPaneTop.revalidate();
        layeredPaneBot.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRoot = new javax.swing.JPanel();
        pnlSide = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_home = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        layeredPaneTop = new javax.swing.JLayeredPane();
        pnlTopHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlBottom = new javax.swing.JPanel();
        layeredPaneBot = new javax.swing.JLayeredPane();
        pnlBotHome = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 700));
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setPreferredSize(new java.awt.Dimension(1100, 700));
        setResizable(false);

        pnlRoot.setLayout(new java.awt.BorderLayout());

        pnlSide.setBackground(new java.awt.Color(51, 66, 87));
        pnlSide.setPreferredSize(new java.awt.Dimension(130, 0));

        jPanel1.setBackground(new java.awt.Color(51, 66, 87));
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 100));

        jLabel1.setBackground(new java.awt.Color(71, 96, 114));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 238, 238));
        jLabel1.setText("Sor daimon");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(35, 35, 35))
        );

        pnlSide.add(jPanel1);

        btn_home.setBackground(new java.awt.Color(84, 140, 168));
        btn_home.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_home.setForeground(new java.awt.Color(238, 238, 238));
        btn_home.setIcon(new javax.swing.ImageIcon("D:\\1.Sor\\IT\\Study\\Java\\Project\\ProjectJava\\src\\main\\java\\com\\mycompany\\projectjava\\icon\\icon_home.png")); // NOI18N
        btn_home.setText("HOME");
        btn_home.setBorder(null);
        btn_home.setBorderPainted(false);
        btn_home.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_home.setPreferredSize(new java.awt.Dimension(130, 60));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
        });
        pnlSide.add(btn_home);

        btn_exit.setBackground(new java.awt.Color(84, 140, 168));
        btn_exit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(238, 238, 238));
        btn_exit.setIcon(new javax.swing.ImageIcon("D:\\1.Sor\\IT\\Study\\Java\\Project\\ProjectJava\\src\\main\\java\\com\\mycompany\\projectjava\\icon\\icon_exit.png")); // NOI18N
        btn_exit.setText("EXIT");
        btn_exit.setBorder(null);
        btn_exit.setBorderPainted(false);
        btn_exit.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_exit.setPreferredSize(new java.awt.Dimension(130, 60));
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        pnlSide.add(btn_exit);

        pnlRoot.add(pnlSide, java.awt.BorderLayout.WEST);

        pnlCenter.setBackground(new java.awt.Color(71, 96, 114));
        pnlCenter.setPreferredSize(new java.awt.Dimension(970, 700));
        pnlCenter.setLayout(new java.awt.BorderLayout());

        pnlTop.setBackground(new java.awt.Color(71, 96, 114));
        pnlTop.setPreferredSize(new java.awt.Dimension(970, 110));
        pnlTop.setLayout(new java.awt.BorderLayout());

        layeredPaneTop.setLayout(new java.awt.CardLayout());

        pnlTopHome.setBackground(new java.awt.Color(71, 96, 114));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(238, 238, 238));
        jLabel2.setText("HOME");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 238, 238));
        jLabel3.setText("Statistics data");

        javax.swing.GroupLayout pnlTopHomeLayout = new javax.swing.GroupLayout(pnlTopHome);
        pnlTopHome.setLayout(pnlTopHomeLayout);
        pnlTopHomeLayout.setHorizontalGroup(
            pnlTopHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTopHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(1458, Short.MAX_VALUE))
        );
        pnlTopHomeLayout.setVerticalGroup(
            pnlTopHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopHomeLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layeredPaneTop.add(pnlTopHome, "card2");

        pnlTop.add(layeredPaneTop, java.awt.BorderLayout.CENTER);

        pnlCenter.add(pnlTop, java.awt.BorderLayout.NORTH);

        pnlBottom.setBackground(new java.awt.Color(71, 96, 114));
        pnlBottom.setLayout(new java.awt.BorderLayout());

        layeredPaneBot.setLayout(new java.awt.CardLayout());

        pnlBotHome.setBackground(new java.awt.Color(238, 238, 238));
        pnlBotHome.setMaximumSize(new java.awt.Dimension(970, 588));
        pnlBotHome.setMinimumSize(new java.awt.Dimension(970, 588));

        javax.swing.GroupLayout pnlBotHomeLayout = new javax.swing.GroupLayout(pnlBotHome);
        pnlBotHome.setLayout(pnlBotHomeLayout);
        pnlBotHomeLayout.setHorizontalGroup(
            pnlBotHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
        pnlBotHomeLayout.setVerticalGroup(
            pnlBotHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotHomeLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(578, Short.MAX_VALUE))
        );

        layeredPaneBot.add(pnlBotHome, "card2");

        pnlBottom.add(layeredPaneBot, java.awt.BorderLayout.CENTER);

        pnlCenter.add(pnlBottom, java.awt.BorderLayout.CENTER);

        pnlRoot.add(pnlCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        // TODO add your handling code here:
        switchPanels(pnlTopHome, pnlBotHome);
    }//GEN-LAST:event_btn_homeMouseClicked

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        // TODO add your handling code here:
        int close = JOptionPane.showConfirmDialog(this, "Do you want to exit?");
        if (close == JOptionPane.YES_OPTION) {
            new LoginGUI().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_exitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLayeredPane layeredPaneBot;
    private javax.swing.JLayeredPane layeredPaneTop;
    private javax.swing.JPanel pnlBotHome;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlRoot;
    private javax.swing.JPanel pnlSide;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel pnlTopHome;
    // End of variables declaration//GEN-END:variables
}
